#!/bin/bash
#PBS -l nodes=2:ppn=16
#PBS -l walltime=1:0:00
#PBS -N Ge
#PBS -V
#PBS -q mpi 

bindir=/shared/ESPRESSO/espresso-6.2.0/bin

input=bands.inp
output=bands.out

mpirun -machinefile $PBS_NODEFILE -np $NPROCS $bindir/bands.x < $input > $output
